# Generated by Django 5.0.dev20230305130119 on 2023-06-02 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
